### ISSUE TITLE
Error: Options passed to a preset which does not accept options

### ISSUE THREAD

**Issue by pragmader** [babel/babel-preset-env#333]
My build started failing on May, 20th with this error message:
```
[2017-05-21T12:01:22.635Z] [ERROR] [catberry:2020] – Error: Options {"targets":{"browsers":["last 2 versions","not ie <= 10"]},"debug":false} passed to a preset which does not accept options. while parsing file: /home/travis/build/catberry/catberry-todomvc/browser.js
    at /home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (/home/travis/build/catberry/catberry-todomvc/node_modules/babelify/index.js:27:24)
```

The code that uses the plugin is here https://github.com/catberry/catberry/blob/9.0.0/lib/builders/BrowserBundleBuilder.js#L367-L396

The Babel related packages have following versions:

```
		"babelify": "^7.3.0",
		"babel-preset-babili": "~0.0.12",
		"babel-preset-env": "^1.2.2",
```

Was working the day before, I have builds scheduled every 12 hours. Nothing has changed from our side.

I've also found the old issue that was describing the same problem https://github.com/babel/babel-preset-env/issues/10

**Comment by existentialism** [comment]
@pragmader thanks for the report, https://github.com/babel/babel-preset-env/releases/tag/v1.5.1 should resolve the issue!

**Comment by xgz123** [comment]
@existentialism 1.5.1 doesn't solve this....

~~~json
{
  "presets": [
    ["env", {
      "es2015": {
        "modules": false
      },
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      }
    }],
    "react"
  ],
  "plugins": ["transform-flow-strip-types", "external-helpers", "transform-decorators-legacy", "transform-object-rest-spread"]
}

~~~

and output:

~~~bash
🚨   (babel plugin) Options {"modules":false} passed to /Users/come/code/carousel/node_modules/babel-preset-react/lib/index.js which does not accept options. (While processing preset: "/Users/come/code/carousel/node_modules/babel-preset-react/lib/index.js")
src/js/index.js
~~~

**Comment by prateekbh** [comment]
same problem as above

**Comment by existentialism** [comment]
@xgz123 @prateekbh can either of you provide a small repo that reproduces the error, would _really_ help!

**Comment by prateekbh** [comment]
sure will try, 
btw i am adding this in `preact-cli` here
https://github.com/developit/preact-cli/blob/master/src/lib/prerender.js#L12

this comes up after adding `ignore: false`

**Comment by prateekbh** [comment]
here's the log 
```
Template execution failed: Error: Options {"loose":true,"modules":"commonjs","uglify":true,"browsers":["> 1%","Last 2 versions","IE >= 9"],"exclude":["transform-regenerator","transform-es2015-typeof-symbol"]} passed to /Users/prateekbh/projects/preact-cli/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/Users/prateekbh/projects/preact-cli/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/Users/prateekbh/projects/preact-cli/node_modules/babel-preset-env/lib/index.js")
  Error: Options {"loose":true,"modules":"commonjs","uglify":true,"browsers":["> 1%","Last 2 versions","IE >= 9"],"exclude":["transform-regenerator","transform-es2015-typeof-symbol"]} passed to /  Users/prateekbh/projects/preact-cli/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/Users/prateekbh/projects/preact-cli/node_modules/babel-  preset-env/lib/index.js") (While processing preset: "/Users/prateekbh/projects/preact-cli/node_modules/babel-preset-env/lib/index.js")
  
  - option-manager.js:314 
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:314:17
  
  - Array.map
  
  - option-manager.js:275 OptionManager.resolvePresets
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:275:20
  
  - option-manager.js:264 OptionManager.mergePresets
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:264:10
  
  - option-manager.js:249 OptionManager.mergeOptions
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:249:14
  
  - option-manager.js:368 OptionManager.init
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:368:12
  
  - node.js:103 compile
    [preact-cli]/[babel-register]/lib/node.js:103:45
  
  - node.js:144 loader
    [preact-cli]/[babel-register]/lib/node.js:144:14
  
  - node.js:154 Object.require.extensions.(anonymous function) [as .js]
    [preact-cli]/[babel-register]/lib/node.js:154:7
  
  - module.js:20 require
    internal/module.js:20:19
  
  - option-manager.js:296 
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:296:17
  
  - Array.map
  
  - option-manager.js:275 OptionManager.resolvePresets
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:275:20
  
  - option-manager.js:264 OptionManager.mergePresets
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:264:10
  
  - option-manager.js:249 OptionManager.mergeOptions
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:249:14
  
  - option-manager.js:368 OptionManager.init
    [preact-cli]/[babel-core]/lib/transformation/file/options/option-manager.js:368:12
  
  - node.js:103 compile
    [preact-cli]/[babel-register]/lib/node.js:103:45
  
  - node.js:144 loader
    [preact-cli]/[babel-register]/lib/node.js:144:14
```

**Comment by prateekbh** [comment]
so removing `loose: true` seems to fix this...
any idea why?

**Comment by xgz123** [comment]
@existentialism thanks! But that didn't solve the problem . I have fixed this by removing `babelrc-rollup` plugin.

**Comment by brandones** [comment]
I ran into this error while working with next.js, also without having changed anything from my side, and with no code of my own calling babel anything or configuring any kind of options.

I solved it by removing some unused dependencies in package.json.
